spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.101.122.176/forum
    username: root
    password: 1122315yx
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
#    sentinel:
#      transport:
#        dashboard: localhost:8080
#      web-context-unify: false
  application:
    name: ceramics-forum
  redis:
    lettuce:
      pool:
        max-wait: -1ms
        max-idle: 8
        max-active: 8
        min-idle: 0
    database: 2
    host: 39.101.122.176
    port: 6379
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 7000
feign:
  client:
    config:
      default:
        connectTimeout: 300000
        readTimeout: 300000
